name: vocalfreq
favicon: null
layout_spectrum: 0.71952
typography_spectrum: 0.4535
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e54e6d'
    - '#82a803'
    - '#01a0b3'
    - '#d5c4b2'
    - '#581000'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
