name: vocalfreq
favicon: null
layout_spectrum: 0.980855
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#280808'
    - '#8898A0'
    - '#C81008'
    - '#F8D060'
  brandStrength: 1
  lightness: 0.0625
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
