analytics: {}
color:
  brandColors:
    - '#000000'
    - '#280808'
    - '#8898A0'
    - '#C81008'
    - '#F8D060'
  brandStrength: 0.3125
  lightness: 0.625
  rhythmicContrast: 0.5
  saturation: 0.375
cta: {}
layout_spectrum: 0.980855
name: vocalfreq
opengraph: {}
purpose: []
typography_spectrum: 1
