layout_spectrum: 0.17678966955281794
typography_spectrum: 0.5986147981602699
color:
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
  brandStrength: 0.8480209396220744
  lightness: 0.73453702731058
  saturation: 0.7657064537052065
  rhythmicContrast: 0.7964083438273519
name: vocalfreq
favicon: null
title: VOCAL FREQ
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74126437-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
