name: vocalfreq
favicon: null
layout_spectrum: 0.47178
typography_spectrum: 0.43966
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#6a4010'
    - '#98bcfa'
    - '#73fe2c'
  brandStrength: 0.3125
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
