name: vocalfreq
favicon: null
layout_spectrum: 0.45854
typography_spectrum: 0.87313
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d5213e'
    - '#748b33'
    - '#12b4a7'
    - '#f49c38'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
