name: vocalfreq
favicon: null
layout_spectrum: 0.36257
typography_spectrum: 1
title: VOCAL FREQ
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74126437-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d5213e'
    - '#748b33'
    - '#12b4a7'
    - '#f49c38'
  brandStrength: 0
  lightness: 0.3125
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
