name: vocalfreq
favicon: null
layout_spectrum: 0.29931
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e54e6d'
    - '#82a803'
    - '#01a0b3'
    - '#d5c4b2'
    - '#581000'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
purpose: []
